import ScheduleAccordion from "./ScheduleAccordion";

export default function ScheduleAccordions({
  monday,
  tuesday,
  wednesday,
  thursday,
  friday,
  saturday,
  sunday,
  handleActivityState,
  handleUpdateDayNote,
  handleUpdateDayDate,
  handleUpdateTimeSlotNote,
  handleLogActivity,
}) {
  return (
    <>
      {monday && (
        <ScheduleAccordion
          day={monday}
          handleActivityState={handleActivityState}
          handleUpdateDayNote={handleUpdateDayNote}
          handleUpdateDayDate={handleUpdateDayDate}
          handleUpdateTimeSlotNote={handleUpdateTimeSlotNote}
          handleLogActivity={handleLogActivity}
        />
      )}
      <ScheduleAccordion
        day={tuesday}
        handleActivityState={handleActivityState}
        handleUpdateDayNote={handleUpdateDayNote}
        handleUpdateDayDate={handleUpdateDayDate}
        handleUpdateTimeSlotNote={handleUpdateTimeSlotNote}
        handleLogActivity={handleLogActivity}
      />
      <ScheduleAccordion
        day={wednesday}
        handleActivityState={handleActivityState}
        handleUpdateDayNote={handleUpdateDayNote}
        handleUpdateDayDate={handleUpdateDayDate}
        handleUpdateTimeSlotNote={handleUpdateTimeSlotNote}
        handleLogActivity={handleLogActivity}
      />
      <ScheduleAccordion
        day={thursday}
        handleActivityState={handleActivityState}
        handleUpdateDayNote={handleUpdateDayNote}
        handleUpdateDayDate={handleUpdateDayDate}
        handleUpdateTimeSlotNote={handleUpdateTimeSlotNote}
        handleLogActivity={handleLogActivity}
      />
      <ScheduleAccordion
        day={friday}
        handleActivityState={handleActivityState}
        handleUpdateDayNote={handleUpdateDayNote}
        handleUpdateDayDate={handleUpdateDayDate}
        handleUpdateTimeSlotNote={handleUpdateTimeSlotNote}
        handleLogActivity={handleLogActivity}
      />
      <ScheduleAccordion
        day={saturday}
        handleActivityState={handleActivityState}
        handleUpdateDayNote={handleUpdateDayNote}
        handleUpdateDayDate={handleUpdateDayDate}
        handleUpdateTimeSlotNote={handleUpdateTimeSlotNote}
        handleLogActivity={handleLogActivity}
      />
      <ScheduleAccordion
        day={sunday}
        handleActivityState={handleActivityState}
        handleUpdateDayNote={handleUpdateDayNote}
        handleUpdateDayDate={handleUpdateDayDate}
        handleUpdateTimeSlotNote={handleUpdateTimeSlotNote}
        handleLogActivity={handleLogActivity}
      />
    </>
  );
}
